<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        \App\Models\Wisata::insert([
            ['nama_wisata'=>'Lembah Hijau','kategori'=>'Wisata Alam','sub_kategori'=>'Taman Alam','alamat'=>'Jl. Radin Intan II, Rajabasa','kelurahan'=>'Rajabasa','kecamatan'=>'Rajabasa','deskripsi'=>'Taman wisata alam dengan berbagai wahana dan pemandangan hijau yang asri.','latitude'=>-5.3760,'longitude'=>105.2430,'jam_operasional'=>'08.00 - 17.00','harga_tiket'=>'25000','fasilitas'=>'Toilet,Mushola,Parkir,Kafe,Spot Foto','kontak'=>'0721-123456','foto'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['nama_wisata'=>'Pantai Duta Wisata','kategori'=>'Wisata Bahari','sub_kategori'=>'Pantai','alamat'=>'Jl. Pantai Duta, Teluk Betung','kelurahan'=>'Bumi Waras','kecamatan'=>'Teluk Betung Selatan','deskripsi'=>'Pantai populer di Bandar Lampung dengan pemandangan laut yang indah.','latitude'=>-5.4900,'longitude'=>105.2750,'jam_operasional'=>'07.00 - 18.00','harga_tiket'=>'15000','fasilitas'=>'Toilet,Parkir,Warung','kontak'=>'0721-234567','foto'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['nama_wisata'=>'Taman Kupu-Kupu Gita Persada','kategori'=>'Wisata Edukasi','sub_kategori'=>'Taman Edukasi','alamat'=>'Jl. Wan Abdul Rahman, Langkapura','kelurahan'=>'Langkapura','kecamatan'=>'Langkapura','deskripsi'=>'Taman konservasi kupu-kupu terbesar di Asia Tenggara.','latitude'=>-5.3920,'longitude'=>105.2190,'jam_operasional'=>'08.00 - 16.00','harga_tiket'=>'20000','fasilitas'=>'Toilet,Mushola,Parkir,Pemandu','kontak'=>'0721-345678','foto'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['nama_wisata'=>'Masjid Al Furqon','kategori'=>'Wisata Religi','sub_kategori'=>'Masjid','alamat'=>'Jl. Soekarno Hatta, Rajabasa','kelurahan'=>'Rajabasa','kecamatan'=>'Rajabasa','deskripsi'=>'Masjid megah ikonik di Kota Bandar Lampung.','latitude'=>-5.3670,'longitude'=>105.2610,'jam_operasional'=>'05.00 - 22.00','harga_tiket'=>null,'fasilitas'=>'Toilet,Mushola,Parkir','kontak'=>'0721-456789','foto'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['nama_wisata'=>'Water Park CitraGarden','kategori'=>'Wisata Keluarga','sub_kategori'=>'Water Park','alamat'=>'Jl. Citra Garden, Kemiling','kelurahan'=>'Kemiling','kecamatan'=>'Kemiling','deskripsi'=>'Wahana air seru untuk keluarga dan anak-anak.','latitude'=>-5.3830,'longitude'=>105.2050,'jam_operasional'=>'09.00 - 17.00','harga_tiket'=>'75000','fasilitas'=>'Toilet,Mushola,Parkir,Kafe,Loker','kontak'=>'0721-567890','foto'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['nama_wisata'=>'Taman Dipangga','kategori'=>'Wisata Budaya/Taman','sub_kategori'=>'Taman Kota','alamat'=>'Jl. Dipangga, Tanjung Karang Pusat','kelurahan'=>'Pelita','kecamatan'=>'Tanjung Karang Pusat','deskripsi'=>'Taman kota yang hijau dan nyaman untuk bersantai.','latitude'=>-5.4240,'longitude'=>105.2600,'jam_operasional'=>'06.00 - 21.00','harga_tiket'=>null,'fasilitas'=>'Toilet,Parkir,Kursi Taman','kontak'=>null,'foto'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['nama_wisata'=>'Tugu Adipura','kategori'=>'Wisata Budaya/Ikon Kota','sub_kategori'=>'Monumen','alamat'=>'Jl. Kartini, Tanjung Karang Pusat','kelurahan'=>'Enggal','kecamatan'=>'Enggal','deskripsi'=>'Ikon Kota Bandar Lampung, monumen kebanggaan warga.','latitude'=>-5.4280,'longitude'=>105.2620,'jam_operasional'=>'24 jam','harga_tiket'=>null,'fasilitas'=>'Parkir','kontak'=>null,'foto'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['nama_wisata'=>'Puncak Mas','kategori'=>'Wisata Alam','sub_kategori'=>'Bukit','alamat'=>'Jl. Puncak Mas, Sukadanaham','kelurahan'=>'Sukadanaham','kecamatan'=>'Tanjung Karang Barat','deskripsi'=>'Destinasi wisata bukit dengan pemandangan kota Bandar Lampung dari ketinggian.','latitude'=>-5.4050,'longitude'=>105.2230,'jam_operasional'=>'07.00 - 18.00','harga_tiket'=>'10000','fasilitas'=>'Toilet,Parkir,Warung,Spot Foto','kontak'=>'0721-678901','foto'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['nama_wisata'=>'Pantai Tirtayasa','kategori'=>'Wisata Bahari','sub_kategori'=>'Pantai','alamat'=>'Jl. Tirtayasa, Teluk Betung Barat','kelurahan'=>'Keteguhan','kecamatan'=>'Teluk Betung Barat','deskripsi'=>'Pantai yang tenang cocok untuk menikmati sunset.','latitude'=>-5.5050,'longitude'=>105.2530,'jam_operasional'=>'06.00 - 18.00','harga_tiket'=>'10000','fasilitas'=>'Toilet,Parkir,Warung','kontak'=>null,'foto'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['nama_wisata'=>'Bukit Sakura','kategori'=>'Wisata Alam','sub_kategori'=>'Bukit','alamat'=>'Jl. Bukit Sakura, Langkapura','kelurahan'=>'Langkapura','kecamatan'=>'Langkapura','deskripsi'=>'Bukit dengan pemandangan indah dan spot foto yang instagramable.','latitude'=>-5.3780,'longitude'=>105.2150,'jam_operasional'=>'07.00 - 18.00','harga_tiket'=>'15000','fasilitas'=>'Toilet,Parkir,Spot Foto','kontak'=>null,'foto'=>null,'created_at'=>now(),'updated_at'=>now()],
        ]);

        \App\Models\Mitigasi::insert([
            ['nama_lokasi'=>'BPBD Kota Bandar Lampung','kategori'=>'Lembaga Pemerintah','jenis_fasilitas'=>'BPBD','sub_jenis'=>'Penanggulangan Bencana','alamat'=>'Jl. Basuki Rahmat No.1, Tanjung Karang','kelurahan'=>'Enggal','kecamatan'=>'Enggal','latitude'=>-5.4260,'longitude'=>105.2580,'jam_operasional'=>'24 jam','kapasitas'=>'50 personel','layanan'=>'Emergency Response,Evakuasi,Posko Bencana','kontak'=>'(0721) 703312','status_aktif'=>'Aktif 24 Jam','created_at'=>now(),'updated_at'=>now()],
            ['nama_lokasi'=>'RSUD Abdul Moeloek','kategori'=>'Rumah Sakit','jenis_fasilitas'=>'Rumah Sakit Umum','sub_jenis'=>'RSUD','alamat'=>'Jl. Dr. Rivai No.6, Enggal','kelurahan'=>'Enggal','kecamatan'=>'Enggal','latitude'=>-5.4215,'longitude'=>105.2555,'jam_operasional'=>'24 jam','kapasitas'=>'500 tempat tidur','layanan'=>'IGD,Rawat Inap,Operasi,ICU','kontak'=>'(0721) 703312','status_aktif'=>'Aktif 24 Jam','created_at'=>now(),'updated_at'=>now()],
            ['nama_lokasi'=>'RSUD A Dadi Tjokrodipo','kategori'=>'Rumah Sakit','jenis_fasilitas'=>'Rumah Sakit Umum','sub_jenis'=>'RSUD','alamat'=>'Jl. Wolter Monginsidi No.235','kelurahan'=>'Gedong Air','kecamatan'=>'Tanjung Karang Barat','latitude'=>-5.4100,'longitude'=>105.2450,'jam_operasional'=>'24 jam','kapasitas'=>'200 tempat tidur','layanan'=>'IGD,Rawat Inap,Rawat Jalan','kontak'=>'(0721) 268384','status_aktif'=>'Aktif 24 Jam','created_at'=>now(),'updated_at'=>now()],
            ['nama_lokasi'=>'Dinas Pemadam Kebakaran','kategori'=>'Dinas Pemerintah','jenis_fasilitas'=>'Damkar','sub_jenis'=>'Pemadam Kebakaran','alamat'=>'Jl. Jend. Sudirman, Tanjung Karang','kelurahan'=>'Enggal','kecamatan'=>'Enggal','latitude'=>-5.4290,'longitude'=>105.2640,'jam_operasional'=>'24 jam','kapasitas'=>'30 armada','layanan'=>'Pemadaman Kebakaran,Penyelamatan','kontak'=>'113','status_aktif'=>'Aktif 24 Jam','created_at'=>now(),'updated_at'=>now()],
            ['nama_lokasi'=>'Lapangan Saburai','kategori'=>'Ruang Terbuka','jenis_fasilitas'=>'Lapangan Evakuasi','sub_jenis'=>'Ruang Evakuasi','alamat'=>'Jl. Gajah Mada, Enggal','kelurahan'=>'Enggal','kecamatan'=>'Enggal','latitude'=>-5.4220,'longitude'=>105.2650,'jam_operasional'=>'24 jam','kapasitas'=>'10000 orang','layanan'=>'Evakuasi,Posko Pengungsian','kontak'=>null,'status_aktif'=>'Aktif','created_at'=>now(),'updated_at'=>now()],
            ['nama_lokasi'=>'Kantor Basarnas Lampung','kategori'=>'Lembaga Pemerintah','jenis_fasilitas'=>'SAR','sub_jenis'=>'Search and Rescue','alamat'=>'Jl. Gatot Subroto, Tanjung Karang','kelurahan'=>'Gedong Air','kecamatan'=>'Tanjung Karang Barat','latitude'=>-5.4150,'longitude'=>105.2500,'jam_operasional'=>'24 jam','kapasitas'=>'20 personel','layanan'=>'Search and Rescue,Evakuasi Laut','kontak'=>'(0721) 702222','status_aktif'=>'Aktif 24 Jam','created_at'=>now(),'updated_at'=>now()],
            ['nama_lokasi'=>'Puskesmas Kedaton','kategori'=>'Fasilitas Kesehatan','jenis_fasilitas'=>'Puskesmas','sub_jenis'=>'Puskesmas Kecamatan','alamat'=>'Jl. Untung Suropati, Kedaton','kelurahan'=>'Kedaton','kecamatan'=>'Kedaton','latitude'=>-5.3920,'longitude'=>105.2630,'jam_operasional'=>'08.00 - 16.00','kapasitas'=>'100 pasien/hari','layanan'=>'Rawat Jalan,Imunisasi,KIA','kontak'=>'(0721) 702112','status_aktif'=>'Aktif','created_at'=>now(),'updated_at'=>now()],
            ['nama_lokasi'=>'PMI Bandar Lampung','kategori'=>'Lembaga Sosial','jenis_fasilitas'=>'PMI','sub_jenis'=>'Palang Merah','alamat'=>'Jl. Teuku Umar, Kedaton','kelurahan'=>'Kedaton','kecamatan'=>'Kedaton','latitude'=>-5.3900,'longitude'=>105.2680,'jam_operasional'=>'08.00 - 16.00','kapasitas'=>'Siap digunakan','layanan'=>'Donor Darah,Ambulan,Pertolongan Pertama','kontak'=>'(0721) 702345','status_aktif'=>'Aktif','created_at'=>now(),'updated_at'=>now()],
            ['nama_lokasi'=>'Terminal Rajabasa','kategori'=>'Infrastruktur','jenis_fasilitas'=>'Terminal','sub_jenis'=>'Titik Evakuasi','alamat'=>'Jl. Radin Intan II, Rajabasa','kelurahan'=>'Rajabasa','kecamatan'=>'Rajabasa','latitude'=>-5.3700,'longitude'=>105.2470,'jam_operasional'=>'24 jam','kapasitas'=>'5000 orang','layanan'=>'Evakuasi,Transportasi Darurat','kontak'=>null,'status_aktif'=>'Aktif','created_at'=>now(),'updated_at'=>now()],
            ['nama_lokasi'=>'Kodim 0410 Bandar Lampung','kategori'=>'Lembaga Militer','jenis_fasilitas'=>'Militer','sub_jenis'=>'Komando Distrik Militer','alamat'=>'Jl. Jend. Sudirman No.10, Enggal','kelurahan'=>'Enggal','kecamatan'=>'Enggal','latitude'=>-5.4270,'longitude'=>105.2570,'jam_operasional'=>'24 jam','kapasitas'=>'Siap digunakan','layanan'=>'Penanggulangan Bencana,Keamanan','kontak'=>'(0721) 252025','status_aktif'=>'Aktif 24 Jam','created_at'=>now(),'updated_at'=>now()],
        ]);
    }
}
